lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private-dev.pem'
    public_key: '%kernel.project_dir%/config/jwt/public-dev.pem'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
