controllers:
    resource: ../../src/Http/Action/
    type: annotation
    defaults:
        _format: json

v1:
    resource: ../../src/Http/Action/V1/
    type: annotation
    prefix: /v1
    defaults:
        _format: json

kernel:
    resource: ../../src/Kernel.php
    type: annotation
