name: Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Docker Compose V2
        run: |
          mkdir -p ~/.docker/cli-plugins/
          curl -SL https://github.com/docker/compose/releases/download/v2.0.0/docker-compose-linux-amd64 -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose

      - uses: actions/checkout@v2

      - name: Cache API Composer
        uses: actions/cache@v2
        with:
          path: api/vendor
          key: api-composer-${{ hashFiles('**/composer.lock') }}

      - name: Change Permissions
        run: sudo chown -R 1000:1000 api

      - name: Dev Init
        run: make init

      - name: Validate Schema
        run: make api-validate-schema

      - name: Lint API
        run: make api-lint

      - name: Analyze API
        run: make api-analyze

      - name: Test API
        run: make api-test